# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
visitor = Role.create!(name:"visitor")
subscriber = Role.create!(name: "subscriber")
admin = Role.create!(name: "admin")
visitor1 = User.create!(email: "hi@gmail.com", password: "whoismy1refuge", role_id: 1)
subscriber1 = User.create!(email: "hi2@gmail.com", password: "whoismy1refuge", role_id: 2)
admin1 = User.create!(email: "hi3@gmail.com", password: "whoismy1refuge", role_id: 3)
Subscription.create!(level:"1", description:"1st_level")
Subscription.create!(level:"2", description:"2nd_level")
Subscription.create!(level:"3", description:"3rd_level")
Order.create!(user_id: 1, subscription_id: 1)
Box.create!(user_id: 1, order_id: 1)
Site.create!(name: "NE Service Center")
Site.create!(name: "NW Service Center")
Site.create!(name: "SE Service Center")
Site.create!(name: "SW Service Center")
Site.create!(name: "5900 Westpark")
Task.create!(name: "Annual Site Inspection-All-SW3P-Members-Wksht-16-X")
Task.create!(name: "Annual Training")
Task.create!(name: "Annual Monitoring-Vendor")
Task.create!(name: "Monthly Oil Water Separator Maintenance-Vendor")
Task.create!(name: "Quarterly Truck Wash-Vendor")
Task.create!(name: "Quarterly Periodic Inspection-PM-Wkst-13")
Task.create!(name: "Quarterly-Visual Monitoring-DAD-FM-Wksht-15")
Task.create!(name: "Semi-Annual-Benchmark Monitoring-Vendor")
Task.create!(name: "Weekly-Routine Facility Inspection-DAD-Wksht-7")
Task.create!(name: "Weekly-Spill response, inventory log-FM-Wksht-8")